### ISSUE TITLE
Thanks and upstream

### ISSUE THREAD

**Issue by todoneunl** [phw/rhythmbox-plugin-listenbrainz#1]
I just want to thank you for this plugin. Works great!

Any change it can be submitted upstream (as an official plugin or shipped 3rd party)?

**Comment by phw** [comment]
Thanks a lot for the nice words.

Upstreaming this was the plan from the start and there is a merge request for this at https://gitlab.gnome.org/GNOME/rhythmbox/merge_requests/9

Unfortunately after resolving some issues there has been no further activity or feedback from upstream authors on this :(

**Comment by phw** [comment]
This plugin is bundled in Rhythmbox 3.4.4 or later.
