### ISSUE TITLE
doesn't seem to work

### ISSUE THREAD

**Issue by ormulum** [phw/rhythmbox-plugin-listenbrainz#2]
a miilion thanks for creating the plug-in. i installed it following the directions here, and when i entered the user token i didn't see any button saying 'submit' or 'next' or anything of that nature, and rhythmbox just froze up, i couldn't close the dialog box in which i'd entered the user token or get back to the main rhythmbox interface. it wouldn't surprise me if the problem lies in the fact that i'm using a cheap computer with ubuntu budgie 19.04, the only linux distribution i could find that connected this lenovo ideapad 130s- 11igm to the internet, i assume it's the only one with the proper driver.
thanks again for providing folks a way to send their listening history to listenbrainz from rhythmbox, i was pleased to see from the previous 'issue' comment that it does work.

**Comment by ormulum** [comment]
oops...
it took a little while but now rhythmbox is sending the information to listenbrainz, another million thanks, i appreciate the work you did to allow us to build up the open source database

**Comment by phw** [comment]
Glad it worked. Just wanted to note that this is also available as a deb package from the MusicBrainz PPA at https://launchpad.net/~musicbrainz-developers/+archive/ubuntu/stable

Also Rhythmbox 3.4.4 includes this plugin now. So in newer Ubuntu versions this plugin will be available if Ubuntu ships Rhythmbox 3.4.4 or later.
